In [1]:
import sqlalchemy
from sqlalchemy import create_engine
import pandas as pd

In [2]:
print(pd.__version__)

1.3.4

In [3]:
print(sqlalchemy.__version__)

1.4.46

In [4]:
# Postgres connection
engine = create_engine('postgresql://root:root@localhost:5432/ny_taxi')

# Query using connection
with engine.connect() as connection:
    df = pd.read_sql("SELECT * FROM ny_taxi_trips LIMIT 10;", connection)

# Exibindo os resultados
display(df)

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,extra,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge
0,2,2019-10-01 00:26:02,2019-10-01 00:39:58,N,1.0,112,196,1.0,5.88,18.0,0.50,0.5,0.00,0.0,None,0.3,19.30,2.0,1.0,0.0
1,1,2019-10-01 00:18:11,2019-10-01 00:22:38,N,1.0,43,263,1.0,0.80,5.0,3.25,0.5,0.00,0.0,None,0.3,9.05,2.0,1.0,0.0
2,1,2019-10-01 00:09:31,2019-10-01 00:24:47,N,1.0,255,228,2.0,7.50,21.5,0.50,0.5,0.00,0.0,None,0.3,22.80,2.0,1.0,0.0
3,1,2019-10-01 00:37:40,2019-10-01 00:41:49,N,1.0,181,181,1.0,0.90,5.5,0.50,0.5,0.00,0.0,None,0.3,6.80,2.0,1.0,0.0
4,2,2019-10-01 00:08:13,2019-10-01 00:17:56,N,1.0,97,188,1.0,2.52,10.0,0.50,0.5,2.26,0.0,None,0.3,13.56,1.0,1.0,0.0
5,2,2019-10-01 00:35:01,2019-10-01 00:43:40,N,1.0,65,49,1.0,1.47,8.0,0.50,0.5,1.86,0.0,None,0.3,11.16,1.0,1.0,0.0
6,1,2019-10-01 00:28:09,2019-10-01 00:30:49,N,1.0,7,179,1.0,0.60,4.0,0.50,0.5,1.00,0.0,None,0.3,6.30,1.0,1.0,0.0
7,2,2019-10-01 00:28:26,2019-10-01 00:32:01,N,1.0,41,74,1.0,0.56,4.5,0.50,0.5,0.00,0.0,None,0.3,5.80,2.0,1.0,0.0
8,2,2019-10-01 00:14:01,2019-10-01 00:26:16,N,1.0,255,49,1.0,2.42,10.5,0.50,0.5,0.00,0.0,None,0.3,11.80,2.0,1.0,0.0
9,1,2019-10-01 00:03:03,2019-10-01 00:17:13,Y,1.0,130,131,1.0,3.40,13.0,0.50,0.5,2.85,0.0,None,0.3,17.15,1.0,1.0,0.0

# Trip Segmentation Count

During the period of October 1st 2019 (inclusive) and November 1st 2019 (exclusive), how many trips, respectively, happened:

- Up to 1 mile
- In between 1 (exclusive) and 3 miles (inclusive),
- In between 3 (exclusive) and 7 miles (inclusive),
- In between 7 (exclusive) and 10 miles (inclusive),
- Over 10 miles

In [5]:
query = """
    SELECT 
    SUM(CASE WHEN trip_distance <= 1 THEN 1 ELSE 0 END) AS TOTAL_TRIPS_UP_TO_1_MILE,
    SUM(CASE WHEN trip_distance > 1 AND trip_distance <= 3 THEN 1 ELSE 0 END) AS TOTAL_TRIPS_BETWEEN_1_AND_3_MILES,
    SUM(CASE WHEN trip_distance > 3 AND trip_distance <= 7 THEN 1 ELSE 0 END) AS TOTAL_TRIPS_BETWEEN_3_AND_7_MILES,
    SUM(CASE WHEN trip_distance > 7 AND trip_distance <= 10 THEN 1 ELSE 0 END) AS TOTAL_TRIPS_BETWEEN_7_AND_10_MILES,
    SUM(CASE WHEN trip_distance > 10 THEN 1 ELSE 0 END) AS TOTAL_TRIPS_OVER_10_MILES
    FROM ny_taxi_trips
    WHERE lpep_dropoff_datetime >= '2019-10-01' AND lpep_dropoff_datetime < '2019-11-01'
    
"""

In [6]:
result = pd.read_sql(query, engine)

In [7]:
result.T

                                         0
total_trips_up_to_1_mile            104802
total_trips_between_1_and_3_miles   198924
total_trips_between_3_and_7_miles   109603
total_trips_between_7_and_10_miles   27678
total_trips_over_10_miles            35189

# Question 4. Longest trip for each day
Which was the pick up day with the longest trip distance? Use the pick up time for your calculations.

Tip: For every day, we only care about one single trip with the longest distance.

In [8]:
query = """
    SELECT
    SUBSTR(lpep_pickup_datetime, 1, 10) AS date,
    trip_distance
    FROM ny_taxi_trips
    ORDER BY trip_distance DESC
    LIMIT 3
"""

In [9]:
result = pd.read_sql(query, engine)

In [10]:
result.head(3)

         date  trip_distance
0  2019-10-31         515.89
1  2019-10-11          95.78
2  2019-10-26          91.56

# Question 5. Three biggest pickup zones
Which were the top pickup locations with over 13,000 in total_amount (across all trips) for 2019-10-18?

Consider only lpep_pickup_datetime when filtering by date.

In [11]:
query = """
    SELECT
    t1."PULocationID",
    t2."Zone",
    SUM(total_amount) AS total_amount
    FROM ny_taxi_trips t1
    LEFT JOIN ny_taxi_zones t2
    ON t1."PULocationID" = t2."LocationID"
    WHERE SUBSTR(lpep_pickup_datetime, 1, 10) = '2019-10-18'
    GROUP BY 1, 2
    HAVING SUM(total_amount) > 13000
    ORDER BY total_amount DESC
"""

In [12]:
result = pd.read_sql(query, engine)

In [13]:
result

   PULocationID                 Zone  total_amount
0            74    East Harlem North      18686.68
1            75    East Harlem South      16797.26
2           166  Morningside Heights      13029.79

# Question 6. Largest tip
For the passengers picked up in October 2019 in the zone named "East Harlem North" which was the drop off zone that had the largest tip?

Note: it's tip , not trip

We need the name of the zone, not the ID.

In [14]:
query = """
    SELECT
    lpep_pickup_datetime,
    t1."PULocationID",
    t1."DOLocationID",
    t2."Zone",
    tip_amount
    FROM ny_taxi_trips t1
    LEFT JOIN ny_taxi_zones t2
    ON t1."DOLocationID" = t2."LocationID"
    WHERE SUBSTR(lpep_pickup_datetime, 1, 7) = '2019-10'
    AND t1."PULocationID" =  74
    ORDER BY tip_amount DESC
"""

In [15]:
result = pd.read_sql(query, engine)

In [16]:
result

,lpep_pickup_datetime,PULocationID,DOLocationID,Zone,tip_amount
0,2019-10-25 15:50:05,74,132,JFK Airport,87.30
1,2019-10-28 06:05:56,74,263,Yorkville West,80.88
2,2019-10-24 14:35:52,74,74,East Harlem North,40.00
3,2019-10-01 00:42:36,74,74,East Harlem North,35.00
4,2019-10-20 15:14:27,74,1,Newark Airport,26.45
...,...,...,...,...,...
37366,2019-10-31 16:29:00,74,159,Melrose South,0.00
37367,2019-10-31 16:01:00,74,51,Co-Op City,0.00
37368,2019-10-31 18:36:00,74,116,Hamilton Heights,0.00
37369,2019-10-02 10:30:20,74,116,Hamilton Heights,0.00
37370,2019-10-15 09:50:19,74,75,East Harlem South,-1.06